# Generated by Django 4.2.5 on 2023-09-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submittes_at',
            new_name='created_at',
        ),
    ]
