# Generated by Django 4.2.5 on 2023-09-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_remove_food_url_delete_foodurls_food_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='url',
        ),
        migrations.CreateModel(
            name='FoodURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='food.food')),
            ],
        ),
    ]
